### PR TITLE
patch multiple fields with same name err case

### PR DESCRIPTION
**Pull request by YaphetsH**
Hello,I met some erroneous with "multiple fields with same name",so I try to deal this case when analysis during resolveField and JClass build.And I pass test with my funny code with two same fields in teh class.

### CODE REVIEW

**Comment by zhangt2333** [comment]
Thank you for actively providing your feedback. 

However, in this PR, the CI is failed, and more tests (minimal reproducible case) and optimization are required.

**Comment by YaphetsH** [comment]
> Thank you for actively providing your feedback.
> 
> In this PR, the CI is failed, and more tests (minimal reproducible case) and optimization are required.

Some err with unit test,I will check and re-commit until fix error messages.

**Comment by zhangt2333** [comment]
If everything is be ready, just push (--force may be required) to the source repo of PR (i.e., the forked repo), and you do not need to create a new PR.

**Comment by YaphetsH** [comment]
> If everything is ready, just push (--force may be required) to the source repo of PR (i.e., the created repo by fork) and reopen this PR, and you do not need to create a new PR.

Sorry to have long time for busy to deal with pr fix, and I think every test is ready fine.Plz check my commit with ambiguous fields err

**Comment by zhangt2333** [comment]
Hi @YaphetsH

Thanks for your work.

However, more tests (minimal reproducible case) are required to illustrate why this PR is essential, i.e., the test was a failure before this PR, and after this PR, the test was a success.

Besides, more optimization (like cache) is required, e.g.,  there may be performance issues in `jclass.getDeclaredFields().stream() ...`.

**Review by zhangt2333 — CHANGES_REQUESTED** [review]
Hi @YaphetsH

Thanks for your work.

However, more tests (minimal reproducible case) are required to illustrate why this PR is essential, i.e., the test was a failure before this PR, and after this PR, the test was a success.

Besides, more optimization (like cache) is required, e.g.,  there may be performance issues in `jclass.getDeclaredFields().stream() ...`.

**Comment by YaphetsH** [comment]
> Hi @YaphetsH
> 
> Thanks for your work.
> 
> However, more tests (minimal reproducible case) are required to illustrate why this PR is essential, i.e., the test was a failure before this PR, and after this PR, the test was a success.
> 
> Besides, more optimization (like cache) is required, e.g., there may be performance issues in `jclass.getDeclaredFields().stream() ...`.

It is not easily to make a funny demo for this test.I met this bug with some android app with proguard that has obscure the overload class member.Here is my test jar which I have extract from target app and convert "*.dex" format file to "*.jar".
You can see "com.xiaomi.mipush.sdk.MessageHandleService" this class file  which  have two same filed named "a"
By the way ,for optimization code way ,I think maybe we have different code style for this project,and for the most reason of pr change,I don't want to change more detail with my code style,so If you test my fix patch pass,you can change my code to your own style(eg. cache with  JClass convert its Jfield with name-type subsignature)
[test.jar.zip](https://github.com/pascal-lab/Tai-e/files/11588002/test.jar.zip)

**Comment by zhangt2333** [comment]
I think it would be more appropriate to propose an issue rather than a PR. And thanks again to your effort. Let us take care of this now

**Comment by zhangt2333** [comment]
Fixed by https://github.com/pascal-lab/Tai-e/compare/576dc141...962ca34

**Comment by YaphetsH** [comment]
> Fixed by [576dc14...962ca34](https://github.com/pascal-lab/Tai-e/compare/576dc141...962ca34)

Thanks,I'll try it.

**Pull request closed without merging**
