### PR TITLE
Fix missing return type in plugin docs

### PR DESCRIPTION
**Pull request by ftyghome**

### CODE REVIEW

**Comment by zhangt2333** [comment]
recheck

**Comment by zhangt2333** [comment]
Thank you for your PR, and sorry for the delayed review.

After reviewing, we look forward to merging your PR. Before that, please sign the CLA according to [this comment](https://github.com/pascal-lab/Tai-e/pull/81#issuecomment-2129442007).

**Comment by ftyghome** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by zhangt2333 — APPROVED** [review]

**Comment by zhangt2333** [comment]
Thanks.

**Pull request merged**
